### ISSUE TITLE
Investigate if Vasturiano library will work with python's showGraph() command. 

### ISSUE THREAD

**Issue by jrmartin** [MetaCell/PsyNeuLinkViewSource#10]
We'll have a format to use to eventually use the d3 force directed layout to visualize the models instead of graphviz which is currently used for showGraph

**Comment by zsinnema** [comment]
@jrmartin 
After investigating the source code of the PsyNeuLink (core) and the rpc_server.py (PsyNeuLinkView) I have the impressions that we should try to use the Graphviz Dot language in the frontend rather than trying to use a JS library in the backend.
The Graphviz Dot language can describe large complex graphs in a way that they can be represented on screen.

My suggestion would be to send the Graphviz source (DOT language) to the Frontend and then transform this into a graph.
We have already a very nice product called Geppetto so I propose to do a POC that will:

1. replace sending of the SVG source with the DOT source representation of the graph to the frontend
2. in the frontend transform the DOT source to a "Geppetto" format
3. use Geppetto to draw the graph

Interesting links:
DOT language: https://www.graphviz.org/doc/info/lang.html
Graphviz: https://www.graphviz.org/about/
JS Visualizer of DOT: http://viz-js.com/

Some DOT examples:
https://graphviz.org/gallery/
https://graphviz.org/Gallery/undirected/save/inet.html
https://graphviz.org/Gallery/directed/crazy.html

you can paste the DOT source into the JS Visualizer of DOT to see the graph/output

**Comment by zsinnema** [comment]
@ddelpiano as discussed today I've assigned this task to you
